# Generated by Django 6.0.6 on 2026-06-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HabitTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "time_success",
                    models.DurationField(
                        verbose_name="Время когда необходимо выполнить привычку"
                    ),
                ),
                (
                    "action",
                    models.TextField(blank=True, null=True, verbose_name="Действие"),
                ),
                (
                    "sign_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки "
                    ),
                ),
                ("periodicity", models.DurationField(verbose_name="Периодичность")),
                (
                    "reward",
                    models.TextField(
                        blank=True, null=True, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "time_complete",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.habittracker",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трекер привычек",
                "verbose_name_plural": "Трекеры привычек",
            },
        ),
    ]
